import type { Metadata } from 'next';
import Footer from '@/components/interaction-elements/Footer';
import './globals.css';
//import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* <Toaster /> */}
        <Footer />
      </body>
    </html>
  );
}
